MovieProject/Controllers/HomePageController.cs
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFrameWork;
using Microsoft.AspNetCore.Mvc;

namespace MovieProject.Controllers
{
	public class HomePageController : Controller
	{

		IFilmService _filmManager;

		public HomePageController(IFilmService filmManger)
		{
			_filmManager = filmManger;
		}

		public IActionResult Index()		
		{
			var values = _filmManager.GetFilmCategoryArtistTake6();
           
            return View(values);
            
		}

		public  PartialViewResult HomePagePartial()
		{		
			return PartialView();
		}

		public PartialViewResult HomePagePartial2()
		{

			return PartialView();
		}




	}
}

MovieProject/ViewComponents/LastFilmsViewComponent.cs
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFrameWork;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace MovieProject.ViewComponents
{
	public class LastFilmsViewComponent:ViewComponent
	{
		//FilmManager _filmManager = new FilmManager(new EFFilmDal());

		IFilmService _filmManager;

        IMemoryCache _memoryCache;

        public LastFilmsViewComponent(IMemoryCache memoryCache,IFilmService filmManager)
		{
			_memoryCache = memoryCache;

			this._filmManager = filmManager;

			Set();
		}

		public void Set()
		{
			var MovieList = _filmManager.GetFilmCategoryArtistTake6();

			_memoryCache.Set("Movies", MovieList, new MemoryCacheEntryOptions
			{
				AbsoluteExpiration = DateTime.Now.AddSeconds(20),

				SlidingExpiration = TimeSpan.FromSeconds(10),

				Priority = CacheItemPriority.Normal
			});
			
		}

        public IViewComponentResult Invoke()
		{
			//var values = _filmManager.GetFilmCategoryArtistTake6();

			if(_memoryCache.TryGetValue<List<Film>>("Movies",out List<Film> values))
			{
				var movies = _memoryCache.Get<List<Film>>("Movies");
				return View(movies);
			}


			return View();

		}


	}
}

MovieProject/Views/HomePage/HomePagePartial.cshtml
@using EntityLayer.Concrete

@model List<Film>

<div class="tab-content" id="myTabContent">
	<div class="tab-pane fade show active" id="tab-1" role="tabpanel" aria-labelledby="1-tab">
		<div class="row">

			@foreach(var item in Model)
			{
			<!-- card -->
			<div class="col-6 col-sm-12 col-lg-6">
				<div class="card card--list">
					<div class="row">
						<div class="col-12 col-sm-4">
							<div class="card__cover">
								<img src="@item.İmageUrl" alt="">
									<a href="/MovieDetail/Index/@item.ID" class="card__play">
									<i class="icon ion-ios-play"></i>
								</a>
							</div>
						</div>

						<div class="col-12 col-sm-8">
							<div class="card__content">
								<h3 class="card__title"><a href="#">@item.Name</a></h3>
								<span class="card__category">
									@foreach(var item2 in item.Categories)
									{
									   <a href="#">@item2.Category.CategoryName</a>									
									}
								</span>

								<div class="card__wrap">
									<span class="card__rate"><i class="icon ion-ios-star"></i>@item.IMDBRaiting</span>

									<ul class="card__list">
										<li>HD</li>
										<li>@item.Age+</li>
									</ul>
								</div>

								<div class="card__description">
									<p>@item.Story</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			}
			<!-- end card -->
			
						
		</div>
	</div>


</div>

MovieProject/Views/HomePage/HomePagePartial2.cshtml
@using EntityLayer.Concrete
@model List<Film>


<section class="section section--bg" data-bg="~/Movie/img/section/section.jpg">
	<div class="container">
		<div class="row">
			<!-- section title -->
			<div class="col-12">
				<h2 class="section__title">Coming Soon...</h2>
			</div>
			<!-- end section title -->
			<!-- card -->
			@foreach(var item in Model)
			{

			<div class="col-6 col-sm-4 col-lg-3 col-xl-2">
				<div class="card">
					<div class="card__cover">
						<img src="@item.İmageUrl" alt="">
						<a href="#" class="card__play">
							<i class="icon ion-ios-play"></i>
						</a>
					</div>
					<div class="card__content">
						<h3 class="card__title"><a href="#">@item.Name</a></h3>
						<span class="card__category">
							@foreach(var item2 in item.Categories)
							{
							<a href="#">@item2.Category.CategoryName</a>
							
							}
						</span>
						<span class="card__rate"><i class="icon ion-ios-star"></i>@item.IMDBRaiting</span>
					</div>
				</div>
			</div>

			}
		
			<div class="col-12">
				<a href="#" class="section__btn">Show more</a>
			</div>
			<!-- end section btn -->
		</div>
	</div>
</section>

MovieProject/Views/HomePage/Index.cshtml
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/GeneralLayout.cshtml";
}

@await Component.InvokeAsync("LastFilms")


<section class="content">
	<div class="content__head">
		<div class="container">
			<div class="row">
				<div class="col-12">
				
					<h2 class="content__title">New Movies</h2>
				
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<!-- content tabs -->
		  

	    @await Html.PartialAsync("HomePagePartial")


		<!-- end content tabs -->
	</div>
</section>
<!-- end content -->
<!-- expected premiere -->
@await Html.PartialAsync("HomePagePartial2")
<!-- end expected premiere -->
<!-- partners -->
<section class="section">


	<div class="container">
		<div class="row">
			<!-- section title -->
			<div class="col-12">
				<h2 class="section__title section__title--no-margin">Our Partners</h2>
			</div>
			<!-- end section title -->
			<!-- section text -->
			<div class="col-12">
				<p class="section__text section__text--last-with-margin">It is a long <b>established</b> fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using.</p>
			</div>
			<!-- end section text -->
			<!-- partner -->
			<div class="col-6 col-sm-4 col-md-3 col-lg-2">
				<a href="#" class="partner">
					<img src="~/Movie/img/partners/themeforest-light-background.png" alt="" class="partner__img">
				</a>
			</div>
			<!-- end partner -->
			<!-- partner -->
			<div class="col-6 col-sm-4 col-md-3 col-lg-2">
				<a href="#" class="partner">
					<img src="~/Movie/img/partners/audiojungle-light-background.png" alt="" class="partner__img">
				</a>
			</div>
			<!-- end partner -->
			<!-- partner -->
			<div class="col-6 col-sm-4 col-md-3 col-lg-2">
				<a href="#" class="partner">
					<img src="~/Movie/img/partners/codecanyon-light-background.png" alt="" class="partner__img">
				</a>
			</div>
			<!-- end partner -->
			<!-- partner -->
			<div class="col-6 col-sm-4 col-md-3 col-lg-2">
				<a href="#" class="partner">
					<img src="~/Movie/img/partners/photodune-light-background.png" alt="" class="partner__img">
				</a>
			</div>
			<!-- end partner -->
			<!-- partner -->
			<div class="col-6 col-sm-4 col-md-3 col-lg-2">
				<a href="#" class="partner">
					<img src="~/Movie/img/partners/activeden-light-background.png" alt="" class="partner__img">
				</a>
			</div>
			<!-- end partner -->
			<!-- partner -->
			<div class="col-6 col-sm-4 col-md-3 col-lg-2">
				<a href="#" class="partner">
					<img src="~/Movie/img/partners/3docean-light-background.png" alt="" class="partner__img">
				</a>
			</div>
			<!-- end partner -->
		</div>
	</div>
</section>